const mongoose = require("mongoose");
const bcrypt = require("bcrypt");

const Schema = mongoose.Schema;

const userSchema = new Schema({
    firstName : String,
    lastName : String,
    otherNames : String,
    fullName : String,
    gender : String,
    birthdayDate : String,
    birthdayTime : String,
    birthdayDateTime : String,
    birthdayTimestamp : Number,
    birthdayDateTimeStamp : Number,
    birthdayYear : String,
    birthdayMonth : String,
    birthdayDay : String,
    birthdayHour : String,
    birthdayMinute : String,
    birthdaySecond : String,
    nextBirthdayCelebrationDate : String,
    nextBirthdayCelebrationTime : String,
    nextBirthdayCelebrationDateTime : String,
    nextBirthdayCelebrationTimestamp : Number,
    nextBirthdayCelebrationDateTimeStamp : Number,
    age : Number,
    ageString : String,
    ageInYears : Number,
    ageInYearsString : String,
    ageInMonths : Number,
    ageInMonthsString : String,
    ageInWeeks : Number,
    ageInWeeksString : String,
    ageInDays : Number,
    ageInDaysString : String,
    ageInHours : Number,
    ageInHoursString : String,
    ageInMinutes : Number,
    ageInMinutesString : String,
    ageInSeconds : Number,
    ageInSecondsString : String,
    defaultPhone: {type : String , unique : true},
    phones : [{type : String , unique : true}],
    defaultEmail : {type : String , unique : true},
    emails : [{type : String , unique : true}],
    password : String,
    country: String,
    countryCode: String,
    timeZone : String,
    timeZoneOffset : String,
    groups : [{type: Schema.Types.ObjectId, ref: 'Group', required: false}],
    tasks : [{type: Schema.Types.ObjectId, ref: 'Task', required: false}],
    tasksCompleted : Number,
    tasksTotal : Number,
    tasksCompletionPercentage : Number,
    tasksCompletionPercentageString : String,
    tasksOverdue : Number,
    tasksOverduePercentage : Number,
    tasksOverduePercentageString : String,
    tasksOverdueToday : Number,
    tasksOverdueTodayPercentage : Number,
    tasksOverdueTodayPercentageString : String,
    tasksOverdueTomorrow : Number,
    tasksOverdueTomorrowPercentage : Number,
    tasksOverdueTomorrowPercentageString : String,
    tasksOverdueThisWeek : Number,
    tasksOverdueThisWeekPercentage : Number,
    tasksOverdueThisWeekPercentageString : String,
    tasksOverdueNextWeek : Number,
    tasksOverdueNextWeekPercentage : Number,
    tasksOverdueNextWeekPercentageString : String,
    tasksOverdueThisMonth : Number,
    tasksOverdueThisMonthPercentage : Number,
    tasksOverdueThisMonthPercentageString : String,
    tasksOverdueNextMonth : Number,
    tasksOverdueNextMonthPercentage : Number,
    tasksOverdueNextMonthPercentageString : String,
    tasksOverdueThisYear : Number,
    tasksOverdueThisYearPercentage : Number,
    tasksOverdueThisYearPercentageString : String,
    tasksOverdueNextYear : Number,
    tasksOverdueNextYearPercentage : Number,
    tasksOverdueNextYearPercentageString : String,
    tasksOverdueTotal : Number,
    tasksOverdueTotalPercentage : Number,
    tasksOverdueTotalPercentageString : String,
    tasksCompletedToday : Number,
    tasksCompletedTodayPercentage : Number,
    tasksCompletedTodayPercentageString : String,
    tasksCompletedYesterday : Number,
    tasksCompletedYesterdayPercentage : Number,
    tasksCompletedYesterdayPercentageString : String,
    tasksCompletedThisWeek : Number,
    tasksCompletedThisWeekPercentage : Number,
    tasksCompletedThisWeekPercentageString : String,
    tasksCompletedLastWeek : Number,
    tasksCompletedLastWeekPercentage : Number,
    tasksCompletedLastWeekPercentageString : String,
    tasksCompletedThisMonth : Number,
    tasksCompletedThisMonthPercentage : Number,
    tasksCompletedThisMonthPercentageString : String,
    tasksCompletedLastMonth : Number,
    tasksCompletedLastMonthPercentage : Number,
    tasksCompletedLastMonthPercentageString : String,
    tasksCompletedThisYear : Number,
    tasksCompletedThisYearPercentage : Number,
    tasksCompletedThisYearPercentageString : String,
    tasksCompletedLastYear : Number,
    tasksCompletedLastYearPercentage : Number,
    tasksCompletedLastYearPercentageString : String,
    tasksCompletedTotal : Number,
    tasksCompletedTotalPercentage : Number,
    tasksCompletedTotalPercentageString : String,
    tasksTotalToday : Number,
    tasksTotalTodayPercentage : Number,
    tasksTotalTodayPercentageString : String,
    tasksTotalYesterday : Number,
    tasksTotalYesterdayPercentage : Number,
    tasksTotalYesterdayPercentageString : String,
    tasksTotalThisWeek : Number,
    tasksTotalThisWeekPercentage : Number,
    tasksTotalThisWeekPercentageString : String,
    tasksTotalLastWeek : Number,
    tasksTotalLastWeekPercentage : Number,
    tasksTotalLastWeekPercentageString : String,
    tasksTotalThisMonth : Number,
    tasksTotalThisMonthPercentage : Number,
    tasksTotalThisMonthPercentageString : String,
    tasksTotalLastMonth : Number,
    tasksTotalLastMonthPercentage : Number,
    tasksTotalLastMonthPercentageString : String,
    tasksTotalThisYear : Number,
    tasksTotalThisYearPercentage : Number,
    tasksTotalThisYearPercentageString : String,
    tasksTotalLastYear : Number,
    tasksTotalLastYearPercentage : Number,
    tasksTotalLastYearPercentageString : String,
    friends : [{type: Schema.Types.ObjectId, ref: 'User', required: false}],
    friendsCount : Number,
    friendRequests : [{type: Schema.Types.ObjectId, ref: 'User', required: false}],
    friendRequestsCount : Number,
    friendRequestsSent : [{type: Schema.Types.ObjectId, ref: 'User', required: false}],
    friendRequestsSentCount : Number,
    followers : [{type: Schema.Types.ObjectId, ref: 'User', required: false}],
    followersCount : Number,
    following : [{type: Schema.Types.ObjectId, ref: 'User', required: false}],
    followingCount : Number,
    visibility : String,
    profilePicture : String,
    profilePictureId : String,
    profilePictureUrl : String,
    profilePicturePublicId : String,
    profilePictureVersion : String,
    profilePictureSignature : String,
    profilePictureWidth : String,
    profilePictureHeight : String,
    profilePictureFormat : String,
    profilePictureResourceType : String,
    currentStreak : Number,
    currentStreakStartDate : String,
    longestStreak : Number,
    longestStreakStartDate : String,
    longestStreakEndDate : String,
    allTimeTasks : Number,
    allTimeCompletedTasks : Number,
    allTimeOverdueTasks : Number,
    lastLoginDate : String,
    lastLoginTime : String,
    lastLoginLocation  : String,
    creationDate : String,
    creationTime : String,
    status : String,
    verified : Boolean,
    verificationCode : String,
    verificationCodeExpirationDate : String,
    verificationCodeExpirationTime : String,
    verificationAttempts : Number,
    verificationAttemptsExpirationDate : String,
    verificationAttemptsExpirationTime : String,
    verificationAttemptsExpirationDateTime : String,
    verificationAttemptsExpirationTimestamp : Number,
    verificationAttemptsExpirationDateTimeStamp : Number,
    // premium , stansard , basic , free - accountType
    accountType : String
});


module.exports = mongoose.model("User" , userSchema , "User");